# Generated by Django 5.0.6 on 2024-05-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historicalbook_historicalreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreview',
            name='book',
        ),
    ]
