# Generated by Django 5.0.6 on 2024-05-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_historicalreview_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreview',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='historicalreview',
            name='date_updated',
        ),
    ]
